#!/usr/bin/env php
<?php

/*!
 * Pattern Lab Builder CLI
 *
 * Copyright (c) 2013-2014 Dave Olsen, http://dmolsen.com
 * Licensed under the MIT license
 *
 */

use \PatternLab\Config;
use \PatternLab\Console;
use \PatternLab\Dispatcher;
use \PatternLab\Timer;

$baseDir = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR;
$autoload = $baseDir . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

// auto-load classes
if (file_exists($autoload)) {
    require $autoload;
} else {
    print "it doesn't appear that pattern lab has been set-up yet...\n";
    print "please install pattern lab's dependencies by typing: composer install...\n";
    exit;
}

// start the timer
Timer::start();

// load the options
Console::init();
Config::init($baseDir);

// initialize the dispatcher & note that the config has been loaded
Dispatcher::init();
Dispatcher::getInstance()->dispatch("config.configLoadEnd");

// run the console
Console::run();
